language: cpp
compiler:
  - gcc
before_install:
  - 'ci/before_install.sh'
env:
  global:
  matrix:
    - BUILD_CORE_ONLY=OFF CMAKE_BUILD_TYPE=Debug
    - BUILD_CORE_ONLY=OFF CMAKE_BUILD_TYPE=Release
    - BUILD_CORE_ONLY=ON CMAKE_BUILD_TYPE=Debug
    - BUILD_CORE_ONLY=ON CMAKE_BUILD_TYPE=Release
before_script: cmake .
script:
  - make
  - sudo ldconfig --verbose # So the test executeables can detect libtinyxml2
  - make test
after_failure:
  - cat Testing/Temporary/LastTest.log
  - cat Testing/Temporary/LastTestsFailed.log
