language: cpp

os:
  - linux
  - osx

sudo: required

dist: trusty

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Debug   COVERALLS=OFF
  - BUILD_TYPE=Release COVERALLS=OFF

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug COVERALLS=ON COVERALLS_REPO_TOKEN=FKh1HgwfV5uzNrYxIT6ZWjcFqybYZSUym
  exclude:
    - os: osx
      compiler: gcc

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 'ci/install_linux.sh' ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then 'ci/install_osx.sh'   ; fi

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DDART_COVERALLS=$COVERALLS ..
  - make all tutorials examples tests test
  - if [ $COVERALLS = ON ]; then make coveralls; fi

after_failure: 
  - cat Testing/Temporary/LastTest.log
  - cat Testing/Temporary/LastTestsFailed.log

