# Project information
site_name: DART Documentation
repo_url: https://github.com/dartsim/dart.git
repo_name: GitHub
site_description: Dynamic Animation and Robotics Toolkit
# site_favicon: null  # todo: add dart.ico
copyright: ﻿Copyright (c) 2011-2015, Georgia Tech Research Corporation

# Build directories
theme: readthedocs
docs_dir: docs/readthedocs
site_dir: docs/readthedocs/site

