[project]
name = "DART"
version = "6.14.0"
description = "Dynamic Animation and Robotics Toolkit"
authors = ["Jeongseok Lee <jslee02@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]
clean = "rm -rf build"

[dependencies]
assimp = ">=5.3.1,<5.4"
bullet-cpp = ">=3.25,<4"
console_bridge = ">=1.0.2,<1.1"
eigen = ">=3.4.0,<3.5"
fcl = ">=0.7.0,<0.8"
fmt = ">=10.2.1,<10.3"
libccd-double = ">=2.1,<3"
libode = ">=0.16.2,<0.17"
octomap = ">=1.9.8,<1.10"
openscenegraph = ">=3.6.5,<3.7"
spdlog = ">=1.12.0,<1.13"
tinyxml2 = ">=10.0.0,<10.1"
urdfdom = ">=4.0.0,<4.1"
ipopt = ">=3.14.14,<3.15"
nlopt = ">=2.7.1,<2.8"
pagmo = ">=2.19.0,<2.20"
numpy = ">=1.26.4,<1.27"

[build-dependencies]
cmake = "3.22.*"
ninja = ">=1.11.1,<1.12"
pkg-config = ">=0.29.2,<0.30"
pytest = ">=8.1.1,<8.2"
doxygen = ">=1.10.0,<1.11"
setuptools = ">=69.1.1,<69.2"
black = ">=24.2.0,<24.3"
isort = ">=5.13.2,<5.14"
pip = ">=24.0,<25"

[target.linux-64.dependencies]
freeglut = ">=3.2.2,<3.3"

[target.linux-64.tasks]
configure = "cmake -G Ninja -S . -B build -DDART_VERBOSE=ON"
lint = { cmd= "cmake --build build --target format && black . && isort .", depends_on = ["configure"] }
check-lint = { cmd= "black . --check && isort . --check", depends_on = ["configure"] }
build = { cmd = "cmake --build build -j", depends_on = [
    "configure",
] }
build_dartpy = { cmd = "cmake --build build -j --target dartpy", depends_on = [
    "configure",
] }
test = { cmd = "ctest --test-dir build --rerun-failed --output-on-failure", depends_on = [
    "build",
] }
test_dartpy = { cmd = "cmake --build build -j --target pytest", depends_on = [
    "configure",
] }
test_all = { cmd = "cmake --build build -j --target ALL", depends_on = [
    "configure",
] }

[target.linux-64.build-dependencies]
clang-format-14 = ">=14.0.6,<14.1"

[target.osx-64.tasks]
configure = "cmake -G Ninja -S . -B build -DDART_VERBOSE=ON"
lint = { cmd= "cmake --build build --target format && black . && isort .", depends_on = ["configure"] }
check-lint = { cmd= "cmake --build build --target check-format && black . --check && isort . --check", depends_on = ["configure"] }
build = { cmd = "cmake --build build -j", depends_on = [
    "configure",
] }
build_dartpy = { cmd = "cmake --build build -j --target dartpy", depends_on = [
    "configure",
] }
test = { cmd = "ctest --test-dir build --rerun-failed --output-on-failure", depends_on = [
    "build",
] }
test_dartpy = { cmd = "cmake --build build -j --target pytest", depends_on = [
    "configure",
] }
test_all = { cmd = "cmake --build build -j --target ALL", depends_on = [
    "configure",
] }

[target.osx-64.build-dependencies]
clang-format-14 = ">=14.0.6,<14.1"

[target.osx-arm64.tasks]
configure = "cmake -G Ninja -S . -B build -DDART_VERBOSE=ON"
lint = { cmd= "cmake --build build --target format && black . && isort .", depends_on = ["configure"] }
check-lint = { cmd= "cmake --build build --target check-format && black . --check && isort . --check", depends_on = ["configure"] }
build = { cmd = "cmake --build build -j", depends_on = [
    "configure",
] }
build_dartpy = { cmd = "cmake --build build -j --target dartpy", depends_on = [
    "configure",
] }
test = { cmd = "ctest --test-dir build --rerun-failed --output-on-failure", depends_on = [
    "build",
] }
test_dartpy = { cmd = "cmake --build build -j --target pytest", depends_on = [
    "configure",
] }
test_all = { cmd = "cmake --build build -j --target ALL", depends_on = [
    "configure",
] }

[target.osx-arm64.build-dependencies]
clang-format-14 = ">=14.0.6,<14.1"

[target.win-64.dependencies]
freeglut = ">=3.2.2,<3.3"

[target.win-64.tasks]
configure = "cmake -S . -B build -G 'Visual Studio 17 2022' -DCMAKE_BUILD_TYPE=Release -DDART_MSVC_DEFAULT_OPTIONS=ON -DBUILD_SHARED_LIBS=OFF -DDART_VERBOSE=ON"
lint = { cmd= "black . && isort .", depends_on = ["configure"] }
check-lint = { cmd= "black . --check && isort . --check", depends_on = ["configure"] }
build = { cmd = "cmake --build build --config Release -j", depends_on = [
    "configure",
] }
build_dartpy = { cmd = "cmake --build build -j --target dartpy", depends_on = [
    "configure",
] }
test = { cmd = "ctest --test-dir build --build-config Release --rerun-failed --output-on-failure", depends_on = [
    "build",
] }
test_dartpy = { cmd = "cmake --build build --config Release -j --target pytest", depends_on = [
    "configure",
] }
test_all = { cmd = "cmake --build build --config Release -j --target ALL", depends_on = [
    "configure",
] }

[target.win-64.build-dependencies]
freeglut = ">=3.2.2,<3.3"
