# https://github.com/orgs/community/discussions/26256#discussioncomment-8756475

name: Remove Expired Workflows
on:
  schedule: [{ cron: "0 3 * * 0" }] # Run every Sunday at 3 AM
  workflow_dispatch:

jobs:
  clean:
    name: Delete Expired Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action Code
        uses: actions/checkout@v4

      - name: Run Delete Script
        run: sh ./scripts/cleanup.sh dartsim dart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
